CREATE TABLE BUYLIST(
   BUYID INT PRIMARY KEY,
   MID VARCHAR(20) NOT NULL,
   PID INT NOT NULL,
   BUYDATE DATE DEFAULT SYSDATE,
   BUYCNT INT DEFAULT 1,
   SHIPPING VARCHAR(300) NOT NULL,
   PRCADR VARCHAR(300) NOT NULL
);

DROP TABLE BUYLIST;
SELECT * FROM BUYLIST;