CREATE TABLE MEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	MPW VARCHAR(50) NOT NULL,
	MNAME VARCHAR(30) NOT NULL,
	STREETADDRESS VARCHAR(300) NOT NULL,
	ZIPCODE VARCHAR(15) NOT NULL,
	ADDRESS VARCHAR(300) NOT NULL,
	MPHONE VARCHAR(50) NOT NULL,
	MILEAGE INT DEFAULT 0 
);
DROP TABLE MEMBER;
SELECT * FROM MEMBER;